### ISSUE TITLE
Es imposible ganar la partida

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#22]
El contador se actualiza en el fichero top_ui.gd:

```
func get_total_seats():
	var current_sum = 0.0
	for i in goal_container.get_child_count():
		current_sum += goal_container.get_child(i).current_number
	return current_sum
```

Ahora mismo sube de 3 en 3 (las fichas), es imposible llegar a 150 en el tiempo establecido.

Hay que pensar una solucion, o inventamos combos o algo sencillito con lo que llegar.

**Comment by dastasoft** [comment]
Los combos "involuntarios" (segundos combos) dan mas puntos

**Comment by dastasoft** [comment]
Activamos el codigo que ya tenemos preparado para las row/column/adjacent/color bombs

**Comment by jamdominguez** [comment]
Cambiando el valor de las piezas más añadiendo "bombas" es posible llegar a los 350 escaños. Sería ideal añadir una opción de selección de dificultad en el menú

**Comment by jamdominguez** [comment]
El valor 2 por pieza junto a las piezas de combinación ajustan la dificultad del juego.
Ahora es desafiante.
