### ISSUE TITLE
Faltan sonidos de partidos

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#24]
Faltan 3 frases para cada partido en los links de 4+ piezas +1 adicional para la pantalla de win.

Hay que revisar si el codigo ya esta preparado para esto pero creo que si, en cualquier caso hay que recabar y cortar los sonidos y dejarlos preparados en el proyecto.

**Comment by jamdominguez** [comment]
Solucionado en issue Paneles de win por partido + sonido #25

**Comment by jamdominguez** [comment]
Añadidos 3 cortes por partido y uno para la bomba de colores
