### ISSUE TITLE
Paneles de win por partido + sonido

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#25]
Faltan los paneles de win para cada partido, el panel debe contener:
- Foto del dirigente
- Sonido de frase del dirigente

El código ya esta preparado a nivel de sacar una pantalla de win, creo recordar que tambien le pasariamos la imagen en el momento de abrir el panel.

**Comment by dastasoft** [comment]
Necesitamos un panel para cuando hay empate entre partidos, simplemente que ponga EMPATE y alguna imagen.

**Comment by jamdominguez** [comment]
Se asocian los partidos a los colores de las fichas para cargar el png correspondiente.
Se evalúa quien gana y si hay empate se muestra una imagen "sin partido"

**Comment by jamdominguez** [comment]
Falta el sonido del ganador

**Comment by jamdominguez** [comment]
Sonido por partido añadido por AlvarJM en mp3.
Lo he convertido a ogg que ocupa menos y asignado a cada partido usando diccionarios.
