### ISSUE TITLE
Sprites para las bombs

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#31]
Sprites para las row/column/adjacent/color bombs de cada partido.

**Comment by jamdominguez** [comment]
Cambiar las bombas por "billetes" o "urnas", la bomba multicolor podría ser una "black card"

**Comment by jamdominguez** [comment]
Cambio de "billetes" por bolsas de billetes con el simbolo del dolar

**Comment by jamdominguez** [comment]
AlvarJM añadió las imagenes de las  urnas y salen correctamente
