### ISSUE TITLE
Añadir botones en el panel de pausa

### ISSUE THREAD

**Issue by jamdominguez** [The-Four-Lords/CongressCrush#38]
Actualmente en el menú hay 2 botones:
"Quit" quita el juego
"Continue" continua con la misma partida

Añadir dos botones en el menú de pausa:
"Reiniciar" que reiniciará la partida
"Salir al menú" que saldrá al menú principal

@hujal54 neceistaría la parte gráfica del panel y ya añadiría el código.

**Comment by jamdominguez** [comment]
Si ganas sale:
"Continue" que reinicia la partida

Si pierdes sale:
"Quit" que quita el juego
"Restart" que lleva al menu de pausa

Se pueden aprovechar estos botones y habrá que "rebautizarlos" porque botones con mismo nombre hacen cosas diferentes en distintos paneles. Puede producir confusiones.

**Comment by hujal54** [comment]
Yo haría que el "Quit" te llevase al menú directamente. No tiene sentido un botón para salir de la aplicación.

Pausa:
"Quit"
"Continue"

Ganas:
"Continue o Restart"

Pierdes:
"Restart"
"Quit"

**Comment by dastasoft** [comment]
Los botones ahora no van

**Comment by jamdominguez** [comment]
Botones de end game arreglados
