### ISSUE TITLE
Minimizar tamaño

### ISSUE THREAD

**Issue by jamdominguez** [The-Four-Lords/CongressCrush#42]
- Refactorizar codigo en la medida de lo posible (con visturí)
- Pasar todos los audios a .ogg
- No tener imágenes repetidas ni que no se usen

El fin es reducir el tamaño de la aplicación.

**Comment by dastasoft** [comment]
Godot tiene una tool instalada que te detecta archivos huerfanos, mirala con cariño a ver si sirve para quitar mas lastre.

![image](https://user-images.githubusercontent.com/45243062/65713556-b6066000-e099-11e9-8ba8-527424d1261f.png)
