### ISSUE TITLE
Botones Bottom UI

### ISSUE THREAD

**Issue by hujal54** [The-Four-Lords/CongressCrush#44]
Añadir botones para silenciar música y silenciar efectos en el Bottom UI de Game Window.

(Talvez también un botón de reset?)

**Comment by jamdominguez** [comment]
- Logica añadida (controla el volumen y resetea al reiniciar la partida)
- Texturas añadidas para musica y efectos

**Comment by dastasoft** [comment]
- El boton de silenciar la musica funciona con la musica de background pero no con las de win.
- El boton de silenciar todo, no hace nada, cambia el icono pero no silencia nada.

**Comment by hujal54** [comment]
El botón de silenciar todo no existe, se trata de silenciar efectos: el burbujeo, frases de políticos y win
El botón de silenciar musica es solo para la de background

**Comment by jamdominguez** [comment]
Terminado
