### ISSUE TITLE
Escaños suman mas de 350

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#56]
Al terminar la partida se dan puntuaciones por encima de los 350 si se suman todos los resultados.

**Comment by jamdominguez** [comment]
Supongo que aun no lo has subido.
He hehco una prueba:
50 puntos por pieza,
Amarillo y rojo van empatados (150)

Hago un combo de 4 con naranja (200) aunque como ya el contador debería ir 2*150=300 sólo debería haber contando 50, quedando el marcador 150 150 50 y no 200 150 150 que da la sensación que ha ganado naranja y no que haya habido empate (como correctamente se ha detectado)

![image](https://user-images.githubusercontent.com/32328074/66210819-ffb70200-e6ba-11e9-9127-b2782cc0680c.png)

**Comment by jamdominguez** [comment]
Al combinar con yelllow (valor de pieza 50), no creo que se de xD
![image](https://user-images.githubusercontent.com/32328074/66230225-027a1d00-e6e4-11e9-91dc-49e879cad034.png)

**Comment by jamdominguez** [comment]
![image](https://user-images.githubusercontent.com/32328074/66230338-3f461400-e6e4-11e9-8270-d5ed0d2d9bf4.png)

**Comment by jamdominguez** [comment]
Se da con puntuación de 50 por pieza, dudo que pase con las puntuaciones normales que manejamos.

**Comment by jamdominguez** [comment]
Jugando normal no se reordena los escaños:
![image](https://user-images.githubusercontent.com/32328074/66230591-ceebc280-e6e4-11e9-8964-7c21da85c12b.png)

Quizás si que habría que hacer un rollback y quedarnos con el mal menor

**Comment by jamdominguez** [comment]
Creo que lo que está pasando es que al reinicar la partida no resetea el valor de los escaños y se queda con los que lleva almacenados (aunque no los muestra) por ello los coloca diferentes:
![image](https://user-images.githubusercontent.com/32328074/66230762-29851e80-e6e5-11e9-8d78-5c8b5811b05a.png)

La puntuación que se ve es jugando normal por 3º o 4º vez seguida.
