### ISSUE TITLE
Dificultad: Column/Row/Adjacent/Color generan tiempo

### ISSUE THREAD

**Issue by dastasoft** [The-Four-Lords/CongressCrush#62]
Mostrar texto flotante con:
- Column/Row Bomb +2s
- Adjacent Bomb +3s
- Color Bomb +5s

Al generar esas bombas, deben sumar esos segundos al tiempo del juego, siempre sin pasarse de 99. Los numeros de segundos son provisionales, hay que testear que se ajusta bien.

Separar bien esta funcionalidad del resto del spagetti plz.

**Comment by jamdominguez** [comment]
@KoshiroKun  @hujal54 test la rama con la feature "time_bonus_develop"
